export const SIZES = {
  icon: 24,
  iconContainer: 48,
  appBarContainer: 64,
  appBarSearchContainer: 56,
  appBarAvatar: 32,
  appBarAvatarText: 16,
  listItemContainer: 56,
  listItemContainer2: 72,
  listItemContainer3: 88,
  listItemAvatar: 40,
  listItemAvatarText: 18,
  listItemTrailingIconContainer: 24,
  listItemTrailingIcon: 20,
}